trigger:
- main 

pool:
  name: 'Default'

steps:
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'kunal-service-connection' 
    appName: 'kunal-webapp' 
    containers: 'kunalregistry.azurecr.io/hello-world:latest' 
